services:
  app:
    build:
      context: .
    tty: true
    working_dir: /workspace
    privileged: true # systemd に必要
    volumes:
      - .:/workspace:rw
      - $HOME/.ssh:/home/ubuntu/.ssh:rw
    tmpfs:
      - /tmp
      - /run
